.TH FTL 1 "December 2024" "FTL Compiler Modules" "FTL Manual"
.SH NAME
FTL Compiler Module \- A easy way to add new keywords to the language.
.SH SYNOPSIS
FTL Compiler modules is a module system that allows for easy adding of language features.
.SH DESCRIPTION
.B ftl
is a compiler that processes source files and generates executable programs, object files, or assembly output depending on the options provided.

.SH SYNTAX
A FTL Compiler Module is defined in a <name>.cm file. The file is split into third parts:

.B KWORD,
.B assembly,
.B and macros.
.TP
.BR KWORD \-
A keyword can be defined with the 'KWORD::' syntax. with a following '<name>;', i.e. 'KWORD::foo;'.
.TP
.BR ASSEMBLY \-
The assembly for you keyword is defined with anything after the ';' in the first line.
.TP
.BR MACROS \-
The macros for you assembly is taken at runtime with anything that begins with '%' followed by a number starting at zero.

.SH EXAMPLES
NOP keyword example
.EX
.EO
KWORD::nop;
  nop
.EC
.EE

.SH BUGS
To report bugs or request features, please visit:
.EX
https://github.com/vx-clutch/ftl/issues
.EE

.SH AUTHOR
Developed and maintained by
.B vx-clutch and other Authors.

.SH COPYRIGHT
Copyright 2024 vx-clutch. Distributed under the terms of the BSD 3-Clause Licence

.SH SEE ALSO
.BR ld (1),
.BR nasm (1),
.BR ftl (1),
