#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER_VERSION "alpha"
#define COMPILER_YEAR "2024"

#define COMPILER_META_TARGET_BUFFER 256

#define MAXINPUTBUFFER 1024
#define MAXOUTPUTPATH 4069

#endif
