#!/usr/bin/env bash

if pwd | grep -q tools; then
  cd ..
fi

header="// Copyright (C) 2024 vx-clutch\n// See end of file for extended copyright information."
footer="
/* ftl is a simple and extensible compiler.
 * Copyright (C) 2024 vx-clutch
 * 
 * The file is part of ftl.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions, and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and the following disclaimer in the documentation or other materials provided with the distribution.
 * 3. Neither the name of vx-clutch nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
"

# If i wanted to i could add auto copyright
# echo -e "$header\n\n$(cat $1)\n$footer" > "$1"

files=$(find ftl -maxdepth 1 \( -name '*.c' -o -name '*.h' \))

if [ -z "$files" ]; then
  echo "No files found"
  exit 0
fi

missing=false

for file in $files; do
  if ! grep -q "Copyright (C)" "$file"; then
    printf "\033[0;31merror\033[0m: file missing copyright: %s\n" "$file"
    missing=true
  fi
done

if [ "$missing" = false ]; then
  echo -e "\033[1;32mAll checks pass\033[0m"
fi
